# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
env:
  matrix:
   - TEST_SDK=iphonesimulator7.0 OS=7.0.3 NAME='iPhone 5'
   - TEST_SDK=iphonesimulator7.0 OS=7.1 NAME='iPhone 5'
   - TEST_SDK=iphonesimulator8.0 OS=8.0 NAME='iPhone 5'
   - TEST_SDK=iphonesimulator8.0 OS=7.0.3 NAME='iPad Retina'

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/Eddystone.xcworkspace -scheme Eddystone-Example -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick